#
name: ARM build Docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
    # Create release
    build-arm64-on-docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Install cross architecture support
          run: sudo apt update && sudo apt-get install -y qemu binfmt-support qemu-user-static # Install the qemu packages

        - name: Register arch support with docker
          run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes # This step will execute the registering scripts

        - name: Check cross arch support
          run: docker run --rm -t arm64v8/ubuntu uname -m # Testing the emulation environment
